version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/yt/static
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: > 
      bash -c " gunicorn -b 0.0.0.0:8000 medical_site.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    volumes:
      - static:/yt/static
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  static: