version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/yt/static
    command: > 
      bash -c "python3 ./manage.py collectstatic --noinput && python ./manage.py migrate  && gunicorn -b 0.0.0.0:8005 medical_site.wsgi:application"
    ports:
      - "8005:8005"
  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - .nginx-conf.d:/etc/nginx/conf.d
      - static:/yt/static
volumes:
  static: