# Generated by Django 4.1 on 2023-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('k_number', models.CharField(max_length=128)),
                ('data_json', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
