# Generated by Django 4.1 on 2023-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
