# Generated by Django 4.1 on 2023-01-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0003_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(),
        ),
    ]
