# Generated by Django 4.1 on 2023-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0004_alter_device_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEnforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128)),
                ('recalling_firm', models.CharField(max_length=128)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
