# Generated by Django 4.1 on 2023-01-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0005_deviceenforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfres_id', models.CharField(max_length=128)),
                ('res_event_number', models.CharField(max_length=128)),
                ('recalling_firm', models.CharField(max_length=128)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
