# Generated by Django 4.1 on 2023-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0006_devicerecall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerecall',
            name='recalling_firm',
            field=models.CharField(max_length=255),
        ),
    ]
