# Generated by Django 4.1 on 2023-01-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0007_alter_devicerecall_recalling_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('medical_specialty_description', models.CharField(max_length=255)),
                ('regulation_number', models.CharField(max_length=32)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
