# Generated by Django 4.1 on 2023-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0008_deviceclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCovid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=16)),
                ('lot_number', models.CharField(max_length=32)),
                ('device', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
