# Generated by Django 4.1 on 2023-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0009_devicecovid19'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pma_number', models.CharField(max_length=16)),
                ('supplement_number', models.CharField(max_length=16)),
                ('applicant', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
