# Generated by Django 4.1 on 2023-01-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0010_devicepma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistrationListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=64)),
                ('fei_number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
