# Generated by Django 4.1 on 2023-01-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0011_deviceregistrationlistings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_device_record_key', models.CharField(max_length=128)),
                ('device_description', models.TextField()),
                ('brand_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
