# Generated by Django 4.1 on 2023-01-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0012_deviceudi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugEnforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('recalling_firm', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
