# Generated by Django 4.1 on 2023-01-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0013_drugenforcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safetyreportid', models.CharField(max_length=64)),
                ('companynumb', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
