# Generated by Django 4.1 on 2023-01-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0014_drugevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugevent',
            old_name='companynumb',
            new_name='company_numb',
        ),
        migrations.RenameField(
            model_name='drugevent',
            old_name='safetyreportid',
            new_name='safety_report_id',
        ),
    ]
