# Generated by Django 4.1 on 2023-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0015_rename_companynumb_drugevent_company_numb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugNDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ndc', models.CharField(max_length=64)),
                ('brand_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
