# Generated by Django 4.1 on 2023-01-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fda', '0018_foodevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugndc',
            old_name='brand_name',
            new_name='labeler_name',
        ),
    ]
